# Gradle settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft / Fabric versions
# Check for newer versions at https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.116.17+1.21.1
junit_version=6.1.3

# Mod properties
mod_version=0.1.0
maven_group=com.sifter
archives_base_name=sifter
